### ISSUE TITLE
tap output fails in tap-dot

### ISSUE THREAD

**Issue by Munter** [Munter/hyperlink#141]
Some errors from tap-render seem to be incompatible with some tap consumers, specifically [tap-dot](https://www.npmjs.com/package/tap-dot) and [am-tap-dot](https://www.npmjs.com/package/am-tap-dot)

```
$ hyperlink build/api/plugins/index.html --root build --canonicalroot https://webpack.js.org | tee plugins.tap | tap-dot

  ...................x/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/trim/index.js:5
  return str.replace(/^\s*|\s*$/g, '');
             ^

TypeError: Cannot read property 'replace' of undefined
    at trim (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/trim/index.js:5:14)
    at Parser._handleError (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/tap-out/index.js:184:14)
    at Parser.handleLine (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/tap-out/index.js:46:8)
    at Stream.<anonymous> (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/tap-out/index.js:212:14)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/through/index.js:45:5)
    at emit (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/split/index.js:37:14)
    at next (/Users/munter/.nvm/versions/node/v8.9.3/lib/node_modules/tap-dot/node_modules/split/index.js:49:7)
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

Minimum recreation that causes this failure:

```tap
TAP version 13
not ok 1 external-check file:///Users/munter/git/webpack.js.org/build/assets/favicon.ico
  ---
    operator: external-check
    expected:
      "200 file:///Users/munter/git/webpack.js.org/build/assets/favicon.ico"
    actual:
      "Unknown error"
    at: build/api/plugins/index.html:9:37 <link rel="shortcut icon" href="/assets/favicon.ico">
  ...
```

**Comment by Munter** [comment]
tap-dot depends on `tap-out`, which apparently a not very good tap parser. Closing as won't fix.

I released https://www.npmjs.com/package/tap-spot which provides dot output, has skip and todo support and has a more compact output
