### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by emartynov** [Munter/hyperlink#4]
Good day!

Sorry for just throwing it on you. but I don't have experience with js and node. I've tried to use tool against our website and got next:

/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/node_modules/jsdom/lib/jsdom/level1/core.js:662
    Array.prototype.splice.call(this._childNodes, oldChildIndex, 1);
                           ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at HTMLDocument.core.Node.removeChild (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/node_modules/jsdom/lib/jsdom/level1/core.js:662:28)
    at HTMLDocument.<anonymous> (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/node_modules/jsdom/lib/jsdom/level2/events.js:370:17)
    at HTMLDocument.proto.(anonymous function) (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/node_modules/jsdom/lib/jsdom/utils.js:23:26)
    at HTMLDocument.inheritFrom.removeChild (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/node_modules/jsdom/lib/jsdom/level1/core.js:1667:47)
    at Html.parseTree (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/assets/Html.js:217:33)
    at Html.extendWithGettersAndSetters.findOutgoingRelationsInParseTree (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/assets/Html.js:252:17)
    at Html.outgoingRelations (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/assets/Asset.js:576:44)
    at Html.extendWithGettersAndSetters.populate (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/assets/Asset.js:635:17)
    at AssetGraph._.extend.addAsset (/usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/index.js:161:15)
    at /usr/local/lib/node_modules/hyperlink/node_modules/assetgraph/lib/transforms/populate.js:106:48

I will try to investigate and fix it on weekend.

**Comment by anselmh** [comment]
Same here.

**Comment by Munter** [comment]
Sorry for the very late answer. I hadn't notice that this project was apparently picking up momentum, so I didn't have watchers on it.

I think this error might be the same one as https://github.com/assetgraph/assetgraph-builder/issues/162

Assetgraph, the engine that drives this tool, is not yet node 0.12 or io.js compatible. Are both of you by any chance on either?

**Comment by emartynov** [comment]
You're probably right I have node 0.12.1 installed

**Comment by Munter** [comment]
I'll make an update to the supported engines in package.json, at least then it's more obvious what the reason is. I don't have any overview of how big the effort will be to make assetgraph IO.js/node 0.12 compatible. I know we have a big hurdle in even going from jsdom 0.x to 1.x because of the way html fragments are handled, so a fix is probably not just around the corner

**Comment by Munter** [comment]
Released in 2.2.0
